apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: <name of pipeline>
  name: <name of pipeline>
spec:
  source:
    git:
      ref: master
      uri: <your git repository>
    sourceSecret:
      name: <name of source secret>
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: <path to Jenkinsfile>
    type: JenkinsPipeline
  triggers:
    - generic:
        secret: secret